<h3>Home - index.phtml</h3>
    
<table class="table">
    <tr>
        <td>aufgezeichnete Messwerte:</td>
        <td><?php echo $totalAmount; ?></td>
    </tr>
    <tr>
        <td>Erste Messung aufgezeichnet am:</td>
        <td><?php echo $dateTimeFirst; ?></td>
    </tr>
    <tr>
        <td>durchschnittliche Temperatur:</td>
        <td><?php echo $averageTemp; ?></td>
    </tr>
    <tr>
        <td>durchschnittliche Windstärke:</td>
        <td><?php echo $averageWind; ?></td>
    </tr>
</table>
    
   